Fix #14: Implementation of the doorhanger UI
mozilla/share-button-study pull request #15
Opened 2017-07-06 22:31 UTC by marcrowo

2017-07-11 18:39 UTC, mythmon requested changes
I have a few suggestions, but overall this looks good. Nice work.

2017-07-11 18:39 UTC, mythmon commented on extension/bootstrap.js
> +      style: "width:400px; height:96px;",
Should this be a part of `panel.css`?

2017-07-11 18:39 UTC, mythmon commented on manual_test.js
> +// const webdriver = require("selenium-webdriver");
You probably don't want this here anymore.

2017-07-11 18:39 UTC, mythmon commented on manual_test.js
> +/* eslint-env node */
You should probably add a comment explaining what this file is for.

2017-07-11 18:39 UTC, mythmon commented on test/button_test.js
> +    await utils.copyUrlBar(driver);
Why do this twice?

2017-07-11 19:02 UTC, marcrowo commented on test/button_test.js
> +    await utils.copyUrlBar(driver);
Oops, that should not be there.

2017-07-11 19:03 UTC, marcrowo commented on manual_test.js
> +// const webdriver = require("selenium-webdriver");
Correct, this is not needed as I moved all of the `webdriver` references to `utils.js`. I think that this is probably better to keep the `button_test.js` as clear and clean as possible.

2017-07-11 19:58 UTC, mythmon approved these changes

2017-07-11 23:12 UTC, marcrowo commented
Having some issues with testing triggering the popup, so I am not merging this yet.

2017-07-13 17:14 UTC, marcrowo commented
Fixes #23: doorhanger tests are now working! Needed to add a window manager for panels to show up. See issue for more details.

2017-07-13 17:16 UTC, merged